# This file is optional

state: development

directories:
    models:      models
    views:       views
    controllers: controllers
    webroot:     webroot
    config:      config
    helpers:     helpers
