development:
    type:     mysql
    host:     localhost
    user:     root
    password:
    database: prank_development

test:
    type:     mysql
    host:     localhost
    user:     root
    password:
    database: prank_test

production:
    type:
    host:
    user:
    password:
    database:
